const CLEAR = 'reminders/CLEAR';
const ADD_REMINDER = 'reminders/ADD_REMINDER';
const REMOVE_REMINDER = 'reminders/REMOVE_REMINDER';
const REMOVE_ALL_REMINDERS = 'reminders/REMOVE_ALL_REMINDERS';

export default {
  CLEAR,
  ADD_REMINDER,
  REMOVE_REMINDER,
  REMOVE_ALL_REMINDERS,
};
